### ISSUE TITLE
打包后，生产环境中css样式不生效

### ISSUE THREAD

**Issue by laterdays** [nonzzz/vite-compression-plugin#10]
打包后，生产环境中css样式不生效

```
 compression({ deleteOriginalAssets: true, include: [/\.(js)$/, /\.(css)$/, /\.(mjs)$/, /\.(json)$/] }),
```

当我使用`vite-plugin-compression`时，样式是正常的  我不确定具体是什么导致这个问题的产生

**Comment by nonzzz** [comment]
这里建议先排查一下`nginx`配置是否正常。`vite-plugin-compression`是否生成了一样的产物。观察前端站点`f12`以后打开`network`对应的css资源里面的`response`是否为`content-type:text/css` 。

**Comment by laterdays** [comment]
@nonzzz   稍后我会对应下是否是一样的产物， content-type 都是text/css，但就是样式是错乱的

**Comment by nonzzz** [comment]
样式错乱指的是?

**Comment by laterdays** [comment]
写的样式不生效，图片被原尺寸显示

**Comment by laterdays** [comment]
![image](https://user-images.githubusercontent.com/112848218/210352935-12f84af3-054b-4d87-92d2-836402c2a118.png)

**Comment by nonzzz** [comment]
查看一下f12. 对应的css source 是否加载。

**Comment by nonzzz** [comment]
@laterdays 我猜你是使用了dynamicImport 导致的问题 （ 这里可以尝试先关闭`deleteOriginalAssets`. nginx还是会优先读取`.gz`文件。 dynamicImport 在bundle阶段没有正确处理。这是一个bug 会进行修复。

**Comment by laterdays** [comment]
@nonzzz 

```
    "@unocss/reset": "^0.48.0",
    "@unocss/runtime": "^0.48.0",
    "@vueuse/core": "^9.9.0",
    "@vueuse/integrations": "^9.9.0",
    "vue": "^3.2.45",
    "vue-i18n": "^9.2.2",
```

```
    "@unocss/preset-icons": "^0.48.0",
    "@unocss/transformer-variant-group": "^0.48.0",
    "@vitejs/plugin-vue": "^4.0.0",
    "@vitejs/plugin-vue-jsx": "^3.0.0",
    "naive-ui": "^2.34.3",
    "npm-run-all": "^4.1.5",
    "unocss": "^0.48.0",
    "unplugin-auto-import": "^0.12.1",
    "unplugin-vue-components": "^0.22.12",
    "vite": "^4.0.3",
    "vite-plugin-compression": "^0.5.1",
    "vite-plugin-svg-icons": "^2.0.1",
```

那应该是的， 期望尽快解决

**Comment by nonzzz** [comment]
@laterdays 已在`0.4.3`版本修复。`example` 也添加了对应的dynamic Import 示例也是按照预期工作。如果这个功能还是有问题 欢迎打开这个问题。

**Comment by laterdays** [comment]
@nonzzz  需要设置algorithm吗 ？ br和gzip哪个比较好点

**Comment by nonzzz** [comment]
@laterdays 插件默认是走`gzip`. `.br`会存在一些兼容性的问题。压缩的建议是把文本类型的进行压缩就好了。图像资源就不要参与压缩了如果图像资源坚持要压缩建议走`.br`。

**Comment by laterdays** [comment]
是否可以在文档中提供下默认压缩的清单， 

例如 
`vite-plugin-compression`  DefaultFilter  `/\.(js|mjs|json|css|html)$/i`

**Comment by nonzzz** [comment]
插件的`include`和`exclude` 默认都是`-`。这个是由用户去决定的。 插件不会做过多的干涉。如果没有设置则会对除了`public`目录底下所引用到的全部模块进行压缩。这一点也和`webpack-plugin-compression`一致。至于为什么和`vben/vite-plugin-compression` 不一样是因为`vite-plugin-compression`的过滤系统过于脆弱。

**Comment by laterdays** [comment]
如果我想设置除了html和图片以外的都压缩，`include: [/\.(js)$/, /\.(mjs)$/, /\.(json)$/, /\.(css)$/] }`  这样是否是正确的 ？

**Comment by nonzzz** [comment]
@laterdays 根据你的正则表达式来看 结果是符合预期的。他只会处理`.js和.mjs`还有`.json,.css`的文件。或者你可以设置`exclude`模块排除`html`和图片资源

**Comment by laterdays** [comment]
如果设置`exclude`， 我不确定图片资源应该具体指定哪些，  `img` `iso` `jpg` `jpeg`  这样看起来`exclude`的比`include`的更多

**Comment by nonzzz** [comment]
那就设置include就好了。 你这样设置是没问题的。

**Comment by laterdays** [comment]
好的，感谢指点， 我会去尝试这样style是否正常，  我有一点疑问，`markdown`文件是否会被压缩呢 ？

**Comment by nonzzz** [comment]
`vite-plugin-compression2` 的工作原理是在生成最终bundle的那个阶段处理你的资源的。 这时候你的`bundle`并不会存在任何`markdown`文件。 他们会被对应的插件翻译成`.js` 内连到`chunk`里面。 一般你只需要设置`js,css,json`的include即可。剩下的特殊情况你可以在观察`dist`根据自己的需要去压缩。而`vite-plugin-compression`是在最后插件结束的周期读取你的`dist`进行压缩操作这里面会存在很多的脏数据同时压缩无意义文件。这也是为什么会有`vite-plugin-compression2`的原因

**Comment by laterdays** [comment]
感谢讲解  ❤

**Comment by laterdays** [comment]
为什么不考虑更名为 `vite-compression-plugin-next`   ，插件名称中带2 感觉有点奇怪

**Comment by nonzzz** [comment]
参照 `json3` @laterdays
