### ISSUE TITLE
安装失败了，是不兼容vite4.0.4吗？

### ISSUE THREAD

**Issue by WangJincheng4869** [nonzzz/vite-compression-plugin#11]
# Bug report 🐞

## Actual results (or Errors)
```
# npm resolution error report

While resolving: basic-paper-cloud-vue3@0.0.0
Found: vite@4.0.4
node_modules/vite
  dev vite@"^4.0.3" from the root project

Could not resolve dependency:
peer vite@"^3.2.3" from vite-plugin-compression2@0.4.3
node_modules/vite-plugin-compression2
  dev vite-plugin-compression2@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by nonzzz** [comment]
pnpm?

**Comment by WangJincheng4869** [comment]
> 

用的npm

**Comment by WangJincheng4869** [comment]
![image](https://user-images.githubusercontent.com/41162158/210974997-6a99ae32-e1aa-4e9f-ba4b-5df75ac75d83.png)

**Comment by nonzzz** [comment]
看起来像是"peerDependencies"的问题。我会移除该字段。进行发布。

**Comment by nonzzz** [comment]
@WangJincheng4869  已经发布了0.5.0版本。进行修复

**Comment by WangJincheng4869** [comment]
> @WangJincheng4869 已经发布了0.5.0版本。进行修复

可以使用了，但是多出个,gz,br的文件，是故意这么设计的吗？
![image](https://user-images.githubusercontent.com/41162158/211269175-002af1d0-e1c3-4b75-8caf-11dcd4e92e5b.png)

**Comment by nonzzz** [comment]
> Reference in new is

能贴一下你的配置吗。他不应该是这样的

**Comment by WangJincheng4869** [comment]
> > Reference in new is
> 
> 能贴一下你的配置吗。他不应该是这样的

```
// https://vitejs.dev/config/
export default defineConfig({
  server: {
    host: '0.0.0.0',
    port: 8180
  },
  resolve: {
    alias: {
      '@' : resolve(__dirname, './src')
    }
  },
  plugins: [
    vue(),
    // https://github.com/intlify/bundle-tools/tree/main/packages/vite-plugin-vue-i18n
    VueI18nPlugin({
      runtimeOnly: true,
      compositionOnly: true,
      include: [resolve("locale/**")]
    }),
    compression(),
    compression({ algorithm: 'brotliCompress'})
  ]
})
```

**Comment by nonzzz** [comment]
看起来配置很正常。和单元测试的结果一致（ 但是生成的结果很诡异。

**Comment by nonzzz** [comment]
我怀疑这是vite在cli和node api的行为不一致导致的（ unit test 采用的是node api caller 的方式进行调用生成的结果是符合预期的。但是我本地测试了一下cli 却不符合预期。我会对此进行排查

**Comment by WangJincheng4869** [comment]
> 我怀疑这是vite在cli和node api的行为不一致导致的（ unit test 采用的是node api caller 的方式进行调用生成的结果是符合预期的。但是我本地测试了一下cli 却不符合预期。我会对此进行排查

好的 谢谢

**Comment by nonzzz** [comment]
如果你觉得`.gz.br`过于丑陋可以先手动修改后缀（ 虽然他目前不影响使用。但是作为UX来说他很糟糕 我会尽快解决

**Comment by nonzzz** [comment]
如果你只是要压缩`.css`和`.js`我建议你先配置`include` @WangJincheng4869 这样可以避免这个问题

**Comment by nonzzz** [comment]
@WangJincheng4869  经过我的思考。 我感觉这是可以通过`include`和`exclude`进行避免这个问题。compression plugin默认是对全文件进行`compress`的。那么设置了多个plugin 实例。那么在整个实例中他们是完全共享了一份`bundle`文件。而第二个实例由于默认是对全文件进行`compress` 那么他得到的`plugin context`是已经修改过的。这点和`vite`无关。如果你想做全文件压缩。而不想配置过多的`include`。我推荐你采用`exclude`。比如`exclude:[/\.(br)$/,/\.(gz)$/]`

**Comment by nonzzz** [comment]
关于这个问题我会在文档额外补充一个说明

**Comment by nonzzz** [comment]
@WangJincheng4869  cc

**Comment by WangJincheng4869** [comment]
> @WangJincheng4869 经过我的思考。 我感觉这是可以通过`include`和`exclude`进行避免这个问题。compression plugin默认是对全文件进行`compress`的。那么设置了多个plugin 实例。那么在整个实例中他们是完全共享了一份`bundle`文件。而第二个实例由于默认是对全文件进行`compress` 那么他得到的`plugin context`是已经修改过的。这点和`vite`无关。如果你想做全文件压缩。而不想配置过多的`include`。我推荐你采用`exclude`。比如`exclude:[/\.(br)$/,/\.(gz)$/]`

完美解决，感谢！

对了，这里设置br会报错，需要设置成brotliCompress
![image](https://user-images.githubusercontent.com/41162158/211279502-31299c2b-ca02-4199-a590-3e2f3c0abfd9.png)

**Comment by nonzzz** [comment]
恩。这是一个`typo`。 我会进行修复

**Comment by nonzzz** [comment]
没什么问题的话这个issue我会进行关闭

**Comment by WangJincheng4869** [comment]
> 没什么问题的话这个issue我会进行关闭

没问题了，OK
