### ISSUE TITLE
使用 `import compression from 'vite-plugin-compression'` 时运行报错 `TypeError: compression is not a function`

### ISSUE THREAD

**Issue by ModyQyW** [nonzzz/vite-compression-plugin#13]
# Bug report 🐞

<https://github.com/ModyQyW/playground>

- yarn install
- yarn dev

## Version & Environment

```shell
$ node -v
v18.13.0
$ yarn -v
1.22.19
```

我已阅读过文档，文档内的建议用法是 `import { compression } from 'vite-plugin-compression'`。

但我倾向于使用默认导入，而且代码内也有默认导出，没有提示类型错误，不太明白为什么不能使用 `import compression from 'vite-plugin-compression'`。

## Expection

正常运行

## Actual results (or Errors)

<img width="581" alt="image" src="https://user-images.githubusercontent.com/31850793/215964579-7537dbad-0746-4844-a569-bb07a0200255.png">

**Comment by nonzzz** [comment]
@ModyQyW  感谢你的反馈。 我查看了你的repo ( 我发现你设置了`type=module` 按照`vite` 自己的逻辑 他会认为他是一个纯esm 这时候原有的导出功能已经不够用了。 我会发布一个新版本解决这个问题。

**Comment by ModyQyW** [comment]
应该在 package.json 里面补 exports 就好了，我可以提一个 pr

**Comment by nonzzz** [comment]
@ModyQyW  嗯。 因为 `type=module` 这种方式 node 需要重新导入模块。欢迎PR

**Comment by nonzzz** [comment]
@ModyQyW `0.6.1` 版本已经发布 可以尝试一下。

**Comment by ModyQyW** [comment]
还是不太正常，把我整不会了。

<img width="1341" alt="image" src="https://user-images.githubusercontent.com/31850793/215971661-c0e5a493-8fb2-4165-a660-60fdbd553274.png">

**Comment by nonzzz** [comment]
这是一个构建错误（ 我会立马修复

**Comment by ModyQyW** [comment]
我还以为是我哪里配置错了 😂

**Comment by nonzzz** [comment]
@ModyQyW  `0.6.2` 已恢复正常

**Comment by ModyQyW** [comment]
一切正常，非常感谢。
