### ISSUE TITLE
opts 应该是可选的

### ISSUE THREAD

**Issue by ModyQyW** [nonzzz/vite-compression-plugin#15]
# Bug report 🐞

opts 应该是可选的，可以通过文档和代码确认这一点。

<img width="520" alt="image" src="https://user-images.githubusercontent.com/31850793/215995340-6c5dfcdf-c513-43d4-bd2e-d35477347ee6.png">

<img width="885" alt="image" src="https://user-images.githubusercontent.com/31850793/215995286-d9c859a9-caf1-4a6c-9169-b001126969fb.png">

## Version & Environment

- vite-plugin-compression2: v0.6.2
- node: 18.13.0
- yarn: 1.22.19
- typescript: 4.9.5

## Expection

opts 应该是可选的。

## Actual results (or Errors)

出现类型错误，必须传入 opts。

<img width="520" alt="image" src="https://user-images.githubusercontent.com/31850793/215995745-c03cc865-d21c-4494-9cf4-4cc723f7034a.png">

类型文件中 `opts` 变成了必选。

<img width="448" alt="image" src="https://user-images.githubusercontent.com/31850793/215995918-d685fcb6-4ee4-410f-a466-8a40ac92a9a1.png">

**Comment by nonzzz** [comment]
@MZ-Dlovely cc.

**Comment by nonzzz** [comment]
@ModyQyW 新版本已发布

**Comment by ModyQyW** [comment]
确认正常。非常感谢。
