### ISSUE TITLE
[vite-plugin-compression] Error running plugin hook generateBundle for vite-plugin-compression, expected a function hook. error during build: Error: Error running plugin hook generateBundle for vite-plugin-compression, expected a function hook.     at error (file:///Users/admin/work/xx/node_modules/.pnpm/rollup@2.77.3/node_modules/rollup/dist/es/shared/rollup.js:1858:30)

### ISSUE THREAD

**Issue by Virgil-N** [nonzzz/vite-compression-plugin#17]
使用pnpm
版本信息：
"vite": "^3.0.7",
"vite-plugin-compression2": "^0.6.3",

报错：
[vite-plugin-compression] Error running plugin hook generateBundle for vite-plugin-compression, expected a function hook. error during build: Error: Error running plugin hook generateBundle for vite-plugin-compression, expected a function hook.     at error (file:///Users/admin/work/xx/node_modules/.pnpm/rollup@2.77.3/node_modules/rollup/dist/es/shared/rollup.js:1858:30)

**Comment by nonzzz** [comment]
感谢关注这个插件。他看起来像是`vite` 版本过低导致的。我觉得你可以尝试升级`vite`版本 比如到`vite@3.1.0`以上。 参照这个: [更新日志](https://github.com/vitejs/vite/blob/v4.1.0-beta.2/packages/vite/CHANGELOG.md#310-2022-09-05)

**Comment by Virgil-N** [comment]
> 感谢关注这个插件。他看起来像是`vite` 版本过低导致的。我觉得你可以尝试升级`vite`版本 比如到`vite@3.1.0`以上。 参照这个: [更新日志](https://github.com/vitejs/vite/blob/v4.1.0-beta.2/packages/vite/CHANGELOG.md#310-2022-09-05)

我更新了vite，重新安装你的插件后，ide提示：Cannot find module 'vite-plugin-compression2' or its corresponding type declarations

**Comment by nonzzz** [comment]
@Virgil-N  因为自从`0.4.3`以后插件默认是支持`v4`。你如果是用的`typescript` 可以给插件的类型`as any`。  下个版本我会优化不同vite版本的类型。

**Comment by nonzzz** [comment]
@Virgil-N `0.7.0` 已发布 可以试一下
