### ISSUE TITLE
The module 'vite-compression-plugin2' or its corresponding type declaration could not be found.

### ISSUE THREAD

**Issue by seafronthu** [nonzzz/vite-compression-plugin#2]
# Bug report 🐞
![image](https://user-images.githubusercontent.com/50374650/200277952-ce49ad92-7ddf-43df-8074-f7cab516562e.png)

**Comment by nonzzz** [comment]
@seafronthu  It's my mistake. you should use `import { compression } from "vite-plugin-compression2";
`. I'll fix the document after soon.

**Comment by seafronthu** [comment]
It's ok. Thank you.
