### ISSUE TITLE
不支持static文件压缩

### ISSUE THREAD

**Issue by nine-fox** [nonzzz/vite-compression-plugin#21]
原来从vite-plugin-compress迁移过来的，但是换成2之后static文件压缩没了。

我们项目里static文件可是多了去了，必须压缩的。。。所以。。。。

强烈建议加上static文件的压缩

**Comment by nonzzz** [comment]
`public direcotry` 一般是用来存放一些~~极小的资源~~ 所以不会对其进行压缩。这是一个需要思考的特性。

**Comment by nonzzz** [comment]
因为根据[vite public directory](https://cn.vitejs.dev/guide/assets.html#the-public-directory) 来看 他是不需要被处理的

**Comment by nine-fox** [comment]
> 因为根据[vite public directory](https://cn.vitejs.dev/guide/assets.html#the-public-directory) 来看 他是不需要被处理的

还真的不是，分场景。比如我现在在做的就是threejs的类似在线游戏的场景。

游玩需要大量的模型文件，比如椅子凳子，每一个都是静态文件，都要引入，不压缩文件巨大。再比如lut的3dl文件，glsl文件，此类文件很多，根本不是bundle文件，他们只需要最后压缩一下处理即可

**Comment by nine-fox** [comment]
我只能先切换回原版compression了

**Comment by nonzzz** [comment]
@nine-fox 了解了。你的这个场景确实会存在这种问题。因为`public` 在传统web项目一般放置的东西足够小。我会在新版支持这个功能

**Comment by nine-fox** [comment]
> @nine-fox 了解了。你的这个场景确实会存在这种问题。因为`public` 在传统web项目一般放置的东西足够小。我会在新版支持这个功能

感谢感谢！

**Comment by nine-fox** [comment]
@nonzzz 太棒了，一天就上线了，今天试了下，it works! 

感谢！
