### ISSUE TITLE
构建完成后控制台输出信息报告缺失

### ISSUE THREAD

**Issue by Bisstocuz** [nonzzz/vite-compression-plugin#24]
# Bug report 🐞

## Version & Environment
```js
  plugins: [
    compression({
      threshold: 1024,
      include: /\.(js|mjs|json|css|html|wasm)$/i,
    }),
    compression({
      algorithm: "brotliCompress",
      threshold: 1024,
      include: /\.(js|mjs|json|css|html|wasm)$/i,
      exclude: /\.(br|gz)$/i,
    })
  ]
```
```json
{
  "dependencies": {
    "@jsquash/png": "^2.0.0",
    "@jsquash/webp": "^1.1.3",
    "axios": "^1.1.3",
    "pinia": "^2.0.17",
    "vfonts": "^0.0.3",
    "vue": "^3.2.37",
    "vue-router": "^4.1.3"
  },
  "devDependencies": {
    "@rushstack/eslint-patch": "^1.1.4",
    "@vitejs/plugin-vue": "^4.0.0",
    "@vitejs/plugin-vue-jsx": "^3.0.0",
    "@vue/eslint-config-prettier": "^7.0.0",
    "eslint": "^8.23.0",
    "eslint-plugin-vue": "^9.4.0",
    "naive-ui": "^2.33.5",
    "prettier": "^2.7.1",
    "vite": "^4.1.4",
    "vite-plugin-cdn-import-rely": "^3.1.0",
    "vite-plugin-compression2": "^0.8.2",
    "vite-plugin-dynamic-import": "^1.2.3",
    "vite-plugin-remove-console": "^2.1.0",
    "vite-plugin-windicss": "^1.8.8",
    "windicss": "^3.5.6"
  }
}
```
## Expection
![image](https://user-images.githubusercontent.com/42398278/224522820-63d30082-ad9f-4e20-9ff3-84822158976e.png)
## Actual results (or Errors)
![image](https://user-images.githubusercontent.com/42398278/224522896-27d6847e-9cea-44d4-ab19-023bb39fa3f7.png)
只有第一层文件夹的 `.gz` 和 `.br` 文件输出到控制台了，但实际上所有文件都正确输出压缩文件到 `dist/` 目录下了。

**Comment by nonzzz** [comment]
看起来像是一个未知错误。`vite-plugin-compression2` 并不负责生成日志。因为所有日志都是交给`vite`接管的。根据
[vite/reporter.ts](https://github.com/vitejs/vite/blob/716286ef21f4d59786f21341a52a81ee5db58aba/packages/vite/src/node/plugins/reporter.ts#L132-L160) 这段逻辑我并没有看出什么异常。

Rollup的`writeBundle` Hook 是发生在`generator` Hook 后面的。那么在处理非`dynamic`的文件他应该是可以正常写入到整个context里面的。没有写入到context的只有那些涉及到`dynamic`的文件。这一点是符合预期的。
@Bisstocuz
