### ISSUE TITLE
exclude设置没有生效 The exclude setting has not taken effect

### ISSUE THREAD

**Issue by Limitless-loong** [nonzzz/vite-compression-plugin#25]
# Bug report 🐞
exclude设置没有生效
The exclude setting has not taken effect

**Comment by nonzzz** [comment]
请提供 配置文件

**Comment by Limitless-loong** [comment]
https://github.com/Limitless-loong/nuxt-demo

**Comment by nonzzz** [comment]
@Limitless-loong  这确实是插件的Bug. 我会尽快进行修复。 感谢你的反馈

**Comment by nonzzz** [comment]
`0.8.4` 已发布。问题已解决
