### ISSUE TITLE
shoud 'continue' when one file not match condition, not 'break'

### ISSUE THREAD

**Issue by Raidennnnnn** [nonzzz/vite-compression-plugin#5]
# Bug report 🐞
filepath: /src/index.ts
![image](https://user-images.githubusercontent.com/13719606/203462488-2b9b742f-0394-4fc1-9b35-43da9d219876.png)

## Version & Environment
no need
## Expection
plugin should loop all files
## Actual results (or Errors)
The plugin stops working directly when it encounters a file that does not meet the conditions

**Comment by nonzzz** [comment]
@Raidennnnnn  Thanks feedback. this is a low level mistake. I'll fix them as soon.
